# Generated by Django 2.2.4 on 2019-08-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190831_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_full_profile', 'Can view a complete profile of other users')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
