# Generated by Django 2.2.4 on 2019-08-26 20:37

from django.db import migrations, models
import src.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', src.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='viacesi_id',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
