# Generated by Django 2.2.4 on 2019-08-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190826_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='viacesi_id',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
