# Generated by Django 2.2.4 on 2019-08-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190826_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_full_profile', 'Is the current user can view all informations about this user')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
