# Generated by Django 2.2.5 on 2019-09-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='support_member',
            field=models.BooleanField(default=False),
        ),
    ]
