# Generated by Django 2.2.4 on 2019-08-27 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='commissions/logos')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='commission/banners')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('deputy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_commissions', to=settings.AUTH_USER_MODEL)),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_commissions', to=settings.AUTH_USER_MODEL)),
                ('treasurer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_commissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
