# Generated by Django 2.2.4 on 2019-08-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_auto_20190831_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='tags',
            field=models.ManyToManyField(blank=True, to='commissions.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
