# Generated by Django 2.2.5 on 2019-09-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_auto_20190831_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='short_description',
            field=models.CharField(max_length=60),
        ),
    ]