# Generated by Django 2.2.5 on 2019-09-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0009_auto_20190924_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='organization_dependant',
            field=models.CharField(choices=[('bde', 'BDE'), ('bds', 'BDS')], default='bde', max_length=100),
        ),
    ]
