# Generated by Django 2.2.6 on 2019-10-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0011_auto_20190930_1819'),
        ('commissions', '0010_event'),
    ]

    operations = [
    ]
