# Generated by Django 2.2.6 on 2019-10-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0012_merge_20191006_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='commissions.Commission'),
        ),
    ]
