# Generated by Django 2.2.6 on 2019-10-15 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commissions', '0012_auto_20191015_1936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membre_Commission',
            new_name='MembreCommission',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='members',
            new_name='membres',
        ),
    ]
