# Generated by Django 2.2.6 on 2019-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0013_auto_20191008_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='short_desc',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
