# Generated by Django 2.2.6 on 2019-10-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0013_auto_20191015_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='membres',
            field=models.ManyToManyField(to='commissions.MembreCommission'),
        ),
    ]
