# Generated by Django 2.2.6 on 2019-11-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0014_auto_20191015_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='is_organization',
            field=models.BooleanField(default=False, help_text="Définie que cet instance est une organisation et non une commission, une organisation n'apparait pas dans la liste des commissions mais dispose de toutes les fonctionnalités associés"),
        ),
    ]
