# Generated by Django 2.2.6 on 2019-10-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0014_auto_20191017_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='membres',
        ),
        migrations.AddField(
            model_name='membrecommission',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission', to='commissions.Commission'),
        ),
    ]
