# Generated by Django 2.2.6 on 2019-10-17 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0015_auto_20191017_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_commissions', to='commissions.Tag'),
        ),
        migrations.AlterField(
            model_name='membrecommission',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membre_commission', to='commissions.Commission'),
        ),
        migrations.AlterField(
            model_name='membrecommission',
            name='identification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membre_identification', to=settings.AUTH_USER_MODEL),
        ),
    ]
