# Generated by Django 2.2.6 on 2019-12-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0016_auto_20191107_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date de publication du post')),
                ('content', models.CharField(max_length=280)),
                ('source', models.CharField(choices=[('internal', 'Système interne'), ('twitter', 'Twitter')], default='internal', help_text='Provenance du post', max_length=50)),
                ('external_id', models.CharField(blank=True, help_text='Identifiant du post sur le site externe (Twitter, Instagram, etc...)', max_length=255, null=True)),
                ('is_moderated', models.BooleanField(default=False, help_text='Si le poste est modéré et masqué aux utilisateurs')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='commissions.Commission')),
            ],
        ),
    ]
