# Generated by Django 2.2.6 on 2019-10-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0016_auto_20191017_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membrecommission',
            name='permission',
        ),
        migrations.AddField(
            model_name='membrecommission',
            name='role',
            field=models.CharField(default='Membre', max_length=20),
        ),
    ]
