# Generated by Django 2.2.6 on 2019-11-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0017_auto_20191017_1919'),
        ('commissions', '0015_commission_is_organization'),
    ]

    operations = [
    ]
