# Generated by Django 2.2.6 on 2019-12-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0020_commissionsocialquester'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.CharField(blank=True, help_text="URL d'image de profil de l'auteur dans le cas ou l'utilisateur est null", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(help_text='Date de publication du post'),
        ),
    ]
