# Generated by Django 2.2.5 on 2019-09-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.BooleanField(default=False),
        ),
    ]
