# Generated by Django 2.2.5 on 2019-09-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20190921_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='role',
            field=models.CharField(choices=[('status', 'Status'), ('reglement-interieur', 'Règlement interieur'), ('status-bds', 'Status du BDS'), ('reglement-interieur-bds', 'Règlement interieur du BDS')], max_length=100),
        ),
    ]
