# Generated by Django 2.2.5 on 2019-09-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20190930_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='current_version',
            field=models.BooleanField(default=False, help_text='Le document est il la dernière version qui sera affichée sur le site'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Le fichier du document pouvant être téléchargé', upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='document',
            name='role',
            field=models.CharField(choices=[('status', 'Status'), ('reglement-interieur', 'Règlement interieur'), ('status-bds', 'Status du BDS'), ('reglement-interieur-bds', 'Règlement interieur du BDS')], help_text='De quel type de document sagit il', max_length=100),
        ),
    ]
