# Generated by Django 2.2.6 on 2019-12-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Court texte de description du lien', max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('weight', models.IntegerField(default=0, help_text='Importance du lien (les plus importants seront les premiers)')),
                ('style', models.CharField(choices=[('standard', 'Standard'), ('special', 'Special')], default='standard', help_text='Style du lien', max_length=50)),
                ('icon', models.CharField(blank=True, default=None, help_text='Icon du lien (format: mdi-[icon])', max_length=255, null=True)),
                ('page', models.CharField(choices=[('index', "Page d'accueil")], help_text="Page d'affichage du lien", max_length=50)),
            ],
        ),
    ]
