# Generated by Django 2.2.6 on 2019-12-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicklink',
            name='page',
            field=models.CharField(choices=[('index', "Page d'accueil")], default='index', help_text="Page d'affichage du lien", max_length=50),
        ),
    ]
