# Generated by Django 2.2.6 on 2019-12-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191201_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicklink',
            name='icon',
            field=models.CharField(blank=True, default=None, help_text='Icon du lien (format: mdi:[icon])', max_length=255, null=True),
        ),
    ]
