# Generated by Django 2.2.4 on 2019-08-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_auto_20190830_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='logo',
            field=models.ImageField(upload_to='commission/logos'),
        ),
    ]
