# Generated by Django 2.2.4 on 2019-08-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_auto_20190830_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
