# Generated by Django 2.2.5 on 2019-09-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_auto_20190831_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='hashtag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='hashtag_definition_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
